---
- name: Discount --> Pis 
  hosts: pis
  become: false  

  vars:
    audio_dir: "/home/{{ ansible_user }}/Desktop/MESH/concepts/Discount/STEMS/DISCOUNT_SUBMIX_"
    video_dir: "{{ ansible_env.HOME }}/Desktop/MESH/concepts/Discount/DiscountVideoScore.mp4"

  tasks:
    
    - name: Play video fullscreen on remote display 0 using VLC
      shell: |
        export DISPLAY=:0
        nohup vlc --fullscreen --play-and-exit "{{ video_dir }}" \
          >/dev/null 2>&1 &
      async: 5
      poll: 0

    - name: play with sclang 
      ansible.builtin.shell: |
        export QT_QPA_PLATFORM=offscreen
        sclang /home/{{ ansible_user }}/Desktop/MESH/concepts/Discount/sc_discount.scd {{ audio_dir }}{{ discount }}.wav
      async: 3600
      poll: 0
      args:
        executable: /bin/bash



- name: Discount --> Bees
  hosts: bees
  become: false  

  vars:

    video_dir: "{{ ansible_env.HOME }}/Desktop/MESH/concepts/Discount/DiscountVideoScore.mp4"

  tasks:
    
    - name: Play video fullscreen on remote display 1 using VLC
      shell: |
        export DISPLAY=:1
        nohup vlc --fullscreen --play-and-exit "{{ video_dir }}" \
          >/dev/null 2>&1 &
      async: 5
      poll: 0
    