- name: Play stems in sync
  hosts: all
  gather_facts: false
  become: false
  vars:
    folder_dir: "/home/{{ ansible_user }}/Desktop/media/numb2"

  tasks:
    - name: Kill all SuperCollider things
      command: killall -9 sclang scsynth
      ignore_errors: true

    - name: Kill all JackTrip things
      command: killall -9 jacktrip
      ignore_errors: true

    - name: Kill all qjacks
      command: killall -9 qjackctl
      ignore_errors: true

    - name: Kill all jackd things
      command: killall -9 jackd
      ignore_errors: true

    - name: Kill all python3 things
      command: killall -9 python3
      ignore_errors: true

    - name: Kill anything using sound devices
      shell: fuser -k /dev/snd/*
      ignore_errors: true


    - name: Pause briefly
      pause:
        seconds: 2

    - name: Get timestamp from pi 1
      shell: echo $(( $(date +%s) + 10 ))
      register: play_at
      when: ansible_host == '10.10.10.11'
      run_once: true

    - name: Play stem at PI 1's timestamp
      shell: |
        #!/bin/bash
        while [ $(date +%s) -lt {{ hostvars['10.10.10.11']['play_at']['stdout'] }} ]; do
          sleep 0.001
        done
        aplay {{ folder_dir }}/{{ index }}.wav
      async: 2592000
      poll: 0