---
- name: Mesh--> Pis 
  hosts: pis
  become: false  

  vars:
    python_dir: "/home/{{ ansible_user }}/Desktop/MESH/concepts/opencv/cv_test_vector.py"
    video_dir: "{{ ansible_env.HOME }}/Desktop/MESH/concepts/Discount/DiscountVideoScore.mp4"

  tasks:
    
    - name: Run openCV on Pis
      become: true
      become_user: student
      environment:
        DISPLAY: ":0"
      ansible.builtin.command: python3 {{ python_dir }}
      async: 9000
      poll: 0


- name: Discount --> Bees
  hosts: bees
  become: false  

  vars: 
    processing_dir: "{{ ansible_env.HOME }}/Desktop/MESH/concepts/opencv/osc_installation"

  tasks: 

    - name: Run Processing sketch on the remote display
      become: false
      environment:
        DISPLAY: ":1"   
        XAUTHORITY: "/home/{{ ansible_user }}/.Xauthority"
      ansible.builtin.command: nohup processing-java --sketch={{ processing_dir }} --run
      async: 9000
      poll: 0

      




      
    