---
- name: Copy entire MESH folder to remote Desktop
  hosts: all
  become: false

  vars:
    # This playbook lives in MESH/setup, so parent dir is the MESH folder
    local_mesh_dir: "{{ playbook_dir }}/.."
    remote_mesh_dir: "/home/student/Desktop/MESH"

  tasks:
    - name: Ensure remote MESH directory exists
      file:
        path: "{{ remote_mesh_dir }}"
        state: directory

    - name: Sync local MESH folder to remote Desktop/MESH (overwrite/mirror)
      synchronize:
        src: "{{ local_mesh_dir }}/"
        dest: "{{ remote_mesh_dir }}/"
        delete: yes      # makes remote match local (removes extra files)
        recursive: yes
        archive: yes
        compress: yes
      # If your control machine is Windows, you may need:
      # delegate_to: localhost
