---
- name: play video using VLC on remote display
  hosts: all
  become: false

  vars:
    # These are passed in via -e
    # desktop_subfolder=MESH
    # remote_video=myvideo.mp4

    # EXAMPLE ansible-playbook setup/send_video_and_play.yml -i config/bees.ini -e "desktop_subfolder=MESH/assets remote_video=test_video.mp4"

    # Build remote_dir automatically per computer
    remote_dir: "{{ ansible_env.HOME }}/Desktop/{{ desktop_subfolder }}"

  tasks:

    - name: Ensure required variables are provided
      assert:
        that:
          - desktop_subfolder is defined
          - remote_video is defined
        fail_msg: >
          Missing required variables!
          Example:
          -e "desktop_subfolder=FOLDER remote_video=file.mp4"

    - name: Ensure remote directory exists
      file:
        path: "{{ remote_dir }}"
        state: directory

    - name: Play video fullscreen on remote display 0 using VLC
      shell: |
        export DISPLAY=:0
        nohup vlc --fullscreen --loop "{{ remote_dir }}/{{ remote_video }}" \
          >/dev/null 2>&1 &
      async: 5
      poll: 0
