---
- name: Copy and play video using VLC on remote display
  hosts: all
  become: false

  vars:
    # These are passed in via -e
    # local_video_dir=/path/to/local/files
    # desktop_subfolder=MESH
    # remote_video=myvideo.mp4

    # Build remote_dir automatically per computer
    remote_dir: "{{ ansible_env.HOME }}/Desktop/{{ desktop_subfolder }}"

  tasks:

    - name: Ensure required variables are provided
      assert:
        that:
          - local_video_dir is defined
          - desktop_subfolder is defined
          - remote_video is defined
        fail_msg: >
          Missing required variables!
          Example:
          -e "local_video_dir=/path desktop_subfolder=FOLDER remote_video=file.mp4"

    - name: Ensure remote directory exists
      file:
        path: "{{ remote_dir }}"
        state: directory

    - name: Check if video already exists on remote
      stat:
        path: "{{ remote_dir }}/{{ remote_video }}"
      register: video_status

    - name: Rsync video if missing
      synchronize:
        src: "{{ local_video_dir }}/{{ remote_video }}"
        dest: "{{ remote_dir }}/"
        mode: push
      when: not video_status.stat.exists

    - name: Play video fullscreen on remote display 0 using VLC
      shell: |
        export DISPLAY=:0
        nohup vlc --fullscreen --play-and-exit "{{ remote_dir }}/{{ remote_video }}" \
          >/dev/null 2>&1 &
      async: 5
      poll: 0
