---
- name: Set desktop wallpaper (LXDE / Raspberry Pi OS)
  hosts: all
  become: true

  vars:
    wallpaper_source: "./background.jpg"          # local file on controller
    wallpaper_dest: "/home/pi/Pictures/wallpaper.jpg"
    lxde_config_dir: "/home/pi/.config/pcmanfm/LXDE-pi"
    lxde_config_file: "{{ lxde_config_dir }}/desktop-items-0.conf"

  tasks:
    - name: Ensure Pictures directory exists
      file:
        path: "/home/pi/Pictures"
        state: directory
        owner: pi
        group: pi
        mode: "0755"

    - name: Copy wallpaper file to Pi
      copy:
        src: "{{ wallpaper_source }}"
        dest: "{{ wallpaper_dest }}"
        owner: pi
        group: pi
        mode: "0644"

    - name: Ensure LXDE config directory exists
      file:
        path: "{{ lxde_config_dir }}"
        state: directory
        owner: pi
        group: pi
        mode: "0755"

    - name: Set wallpaper path
      lineinfile:
        path: "{{ lxde_config_file }}"
        regexp: "^wallpaper="
        line: "wallpaper={{ wallpaper_dest }}"
        create: yes
        owner: pi
        group: pi
        mode: "0644"

    - name: Set wallpaper mode
      lineinfile:
        path: "{{ lxde_config_file }}"
        regexp: "^wallpaper_mode="
        line: "wallpaper_mode=stretch"

    - name: Restart PCManFM to apply wallpaper
      become: false
      shell: |
        pkill pcmanfm || true
        pcmanfm --desktop --profile LXDE-pi &
